# Generated by Django 4.0.3 on 2022-05-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturing_2DG',
            fields=[
                ('m2_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('m2_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturing_4DG',
            fields=[
                ('m4_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('m4_name', models.CharField(max_length=600)),
                ('m2_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSME_app.manufacturing_2dg')),
            ],
        ),
        migrations.CreateModel(
            name='services_2DG',
            fields=[
                ('s2_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('s2_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='services_4DG',
            fields=[
                ('s4_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('s4_name', models.CharField(max_length=600)),
                ('s2_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSME_app.services_2dg')),
            ],
        ),
        migrations.CreateModel(
            name='Trading_2DG',
            fields=[
                ('t2_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('t2_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trading_4DG',
            fields=[
                ('t4_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('t4_name', models.CharField(max_length=600)),
                ('t2_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSME_app.trading_2dg')),
            ],
        ),
        migrations.CreateModel(
            name='Trading_5DG',
            fields=[
                ('t5_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('t5_name', models.CharField(max_length=600)),
                ('t2_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSME_app.trading_2dg')),
                ('t4_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSME_app.trading_4dg')),
            ],
        ),
        migrations.CreateModel(
            name='services_5DG',
            fields=[
                ('s5_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('s5_name', models.CharField(max_length=600)),
                ('s2_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSME_app.services_2dg')),
                ('s4_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSME_app.services_4dg')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturing_5DG',
            fields=[
                ('m5_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('m5_name', models.CharField(max_length=600)),
                ('m2_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSME_app.manufacturing_2dg')),
                ('m4_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSME_app.manufacturing_4dg')),
            ],
        ),
    ]
